site_name: Q Toolkit
use_directory_urls: false
markdown_extensions:
    - toc:
        permalink: true
        baselevel: 1
        toc_depth: 3
    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - pymdownx.superfences
theme:
    name: material

nav:
    - Home: 'index.md'
    - 'Getting Started': 'get_started.md'
    - 'API Reference':
        - '.qtk.db': 'api/qtk_db.md'
        - '.qtk.dict': 'api/qtk_dict.md'
        - '.qtk.err': 'api/qtk_err.md'
        - '.qtk.import': 'api/qtk_import.md'
        - '.qtk.list': 'api/qtk_list.md'
        - '.qtk.os': 'api/qtk_os.md'
        - '.qtk.pdb': 'api/qtk_pdb.md'
        - '.qtk.tbl': 'api/qtk_tbl.md'
        - '.qtk.utils': 'api/qtk_utils.md'
